apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      multiline.pattern: '^[0-9]'
      multiline.negate: true
      multiline.match: after
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
    output.elasticsearch:
      index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:192.167.0.172:9200}'
      protocol: "http"
    setup.template.name: "k8s-log"
    setup.template.pattern: "filebeat-*"
    setup.ilm.enabled: false
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat-fat
  name: filebeat-filebeat-fat-config
  namespace: default
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: filebeat-filebeat-fat
    chart: filebeat-fat-7.6.2
    release: filebeat
  name: filebeat-filebeat-fat
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebeat-filebeat-fat
      release: filebeat
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filebeat-filebeat-fat
        chart: filebeat-fat-7.6.2
        heritage: Helm
        release: filebeat
      name: filebeat-filebeat-fat
    spec:
      containers:
      - args:
        - -e
        - -E
        - http.enabled=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.elastic.co/beats/filebeat:7.6.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: filebeat
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              filebeat test output
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/data
          name: data
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: varrundockersock
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: filebeat-filebeat-fat
      serviceAccountName: filebeat-filebeat-fat
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 384
          name: filebeat-filebeat-fat-config
        name: filebeat-config
      - hostPath:
          path: /var/lib/filebeat-filebeat-fat-default-data
          type: DirectoryOrCreate
        name: data
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: varrundockersock
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: filebeat-filebeat-fat
    release: filebeat
    name: filebeat-filebeat-fat-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"creationTimestamp":"2021-05-06T10:36:59Z","labels":{"app":"filebeat-filebeat-fat","chart":"filebeat-fat-7.6.2","heritage":"Helm","release":"filebeat"},"name":"filebeat-filebeat-fat-cluster-role-binding","resourceVersion":"170303804","selfLink":"/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/filebeat-filebeat-fat-cluster-role-binding","uid":"fece2533-827d-4f1c-b2e9-9de8773a4175"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"filebeat-filebeat-fat-cluster-role"},"subjects":[{"kind":"ServiceAccount","name":"filebeat-filebeat-fat","namespace":"default"}]}
  creationTimestamp: "2021-11-01T06:19:15Z"
  labels:
    app: filebeat-filebeat-fat
    chart: filebeat-fat-7.6.2
    heritage: Helm
    release: filebeat
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-11-01T06:19:15Z"
  name: filebeat-filebeat-fat-cluster-role-binding
  resourceVersion: "3259586"
  uid: 0f97592a-d2bd-45c0-94c1-8578dc29a367
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat-filebeat-fat-cluster-role
subjects:
- kind: ServiceAccount
  name: filebeat-filebeat-fat
  namespace: default
