apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "32109"
    prometheus.io/scrape: "true"
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  CluserIP:
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
    nodePort: 32109
  selector:
    component: etcd
    tier: control-plane
  type: NodePort
