apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["bin/sh", "-c"]
    args:
    - echo $myusername
    env:
    - name: myusername
      valueFrom:
        secretKeyRef:
          name: secret-demo
          key: username

