apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.120.139
    path: '/nfs/data'
---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.120.139
    path: "/nfs/data"

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.120.139
    path: "/nfs/data"

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-pv3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.120.139
    path: "/nfs/data"

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nfs-pv4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.120.139
    path: "/nfs/data"
