apiVersion: v1
data:
  master.conf: |-
    daemonize no
    pidfile "/var/run/redis.pid"
    port 6379
    timeout 300
    loglevel warning
    logfile "redis.log"
    databases 16
    rdbcompression yes
    dbfilename "redis.rdb"
    dir "/data"
    requirepass 123qweasd
    masterauth 123qweasd
    maxclients 10000
    maxmemory 1000mb
    maxmemory-policy allkeys-lru
    appendonly no
    appendfsync always
  sentinel.conf: |-
    daemonize no
    port 26379
    dir "/tmp"
    sentinel monitor mymaster master.redis-cluster 6379 2
    sentinel down-after-milliseconds mymaster 60000
    sentinel auth-pass mymaster 123qweasd
    sentinel config-epoch mymaster 0
    sentinel leader-epoch mymaster 0
  slave.conf: |-
    daemonize no
    pidfile "/var/run/redis.pid"
    port 6379
    timeout 300
    loglevel warning
    logfile "redis.log"
    databases 16
    rdbcompression yes
    dbfilename "redis.rdb"
    dir "/data"
    requirepass 123qweasd
    masterauth 123qweasd
    maxclients 10000
    maxmemory 1000mb
    maxmemory-policy allkeys-lru
    appendonly no
    appendfsync always
    slaveof master.redis-cluster 6379
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: redis-cluster
