apiVersion: v1
kind: Pod
metadata:
  name: configmap-busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c"]
    args:
    - echo $myname; sleep 600
    env:
    - name: myname
      valueFrom: 
        configMapKeyRef:
          name: demo-config
          key: name
    - name: department
      valueFrom:
        configMapKeyRef:
          name: demo-config
          key: dept
